import logging
import os
import ipaddress

from django.core.mail import EmailMultiAlternatives, get_connection
from django.template.loader import render_to_string

from .guides import InstallationGuideService, GuideContext
from .wireguard import WireGuardService
from .qr import generate_qr
from .server import WireGuardServerService

logger = logging.getLogger(__name__)

# ============================================================
# PEER CONFIG GENERATION
# ============================================================

def generate_peer_config(peer) -> str:
    """
    Generate WireGuard peer configuration content.
    Ensures:
    - Endpoint is always host:port (no spaces)
    - No duplicate ports
    - Safe defaults
    """
    private_key = peer.get_private_key()
    server = peer.get_server()
    if not server:
        raise ValueError("Peer has no assigned server")

    raw_endpoint = (server.endpoint or server.public_ip or "").strip()
    if not raw_endpoint:
        raise ValueError(f"Server {server.name} has no endpoint or public IP")

    host_only = raw_endpoint.split(":")[0].strip()
    endpoint = f"{host_only}:{int(server.port)}"

    mtu = server.mtu or 1420
    dns = peer.get_dns() or "8.8.8.8,8.8.4.4"
    keepalive = server.persistent_keepalive or 25
    allowed_ips = peer.get_allowed_ips() or "0.0.0.0/0"

    return f"""[Interface]
PrivateKey = {private_key}
Address = {peer.allowed_ip}/32
DNS = {dns}
MTU = {mtu}

[Peer]
PublicKey = {server.public_key}
Endpoint = {endpoint}
AllowedIPs = {allowed_ips}
PersistentKeepalive = {keepalive}
"""


# ============================================================
# SERVER CONFIG GENERATION (iptables-legacy ONLY)
# ============================================================

def generate_server_config(server, private_key: str) -> str:
    """
    Generate full WireGuard server configuration.
    Uses iptables-legacy only (NO UFW).
    """
    iface = ipaddress.ip_interface(server.server_address)
    server_ip = str(iface.ip)
    network_cidr = str(iface)

    raw_endpoint = (server.endpoint or "").strip()
    endpoint_host = raw_endpoint.split(":")[0] if raw_endpoint else ""
    endpoint = f"{endpoint_host}:{server.port}" if endpoint_host else ""

    iface_name = server.interface or "wg0"
    uplink = server.uplink_interface or "eth0"

    lines = [
        "# =========================================================",
        "# WireGuard Server Configuration",
        "# Generated by WireGuard Auto",
        "# =========================================================",
        "",
        "[Interface]",
        f"# Server Name: {server.name}",
        f"# Public Key: {server.public_key}",
        f"# Endpoint: {endpoint}",
        f"Address = {network_cidr}",
        f"ListenPort = {server.port}",
        f"PrivateKey = {private_key}",
    ]

    if server.dns:
        lines.append(f"DNS = {', '.join(d.strip() for d in server.dns.split(','))}")

    if server.mtu and server.mtu != 1420:
        lines.append(f"MTU = {server.mtu}")

    lines.extend([
        "",
        "# Enable forwarding and NAT (iptables-legacy)",
        f"PostUp = iptables-legacy -A FORWARD -i {iface_name} -j ACCEPT",
        f"PostUp = iptables-legacy -A FORWARD -o {iface_name} -j ACCEPT",
        f"PostUp = iptables-legacy -t nat -A POSTROUTING -s {network_cidr} -o {uplink} -j MASQUERADE",
        "",
        f"PostDown = iptables-legacy -D FORWARD -i {iface_name} -j ACCEPT",
        f"PostDown = iptables-legacy -D FORWARD -o {iface_name} -j ACCEPT",
        f"PostDown = iptables-legacy -t nat -D POSTROUTING -s {network_cidr} -o {uplink} -j MASQUERADE",
    ])

    peers = server.peers.filter(is_active=True)
    if peers.exists():
        lines.append("")
        lines.append(f"# Active Peers ({peers.count()})")
        lines.append("")
        for peer in peers:
            lines.extend([
                "[Peer]",
                f"# Name: {peer.name}",
                f"# Email: {peer.email}",
                f"# Platform: {peer.platform}",
                f"PublicKey = {peer.public_key}",
                f"AllowedIPs = {peer.allowed_ip}/32",
            ])
            if server.persistent_keepalive:
                lines.append(f"PersistentKeepalive = {server.persistent_keepalive}")
            lines.append("")
    else:
        lines.append("")
        lines.append("# No active peers configured yet")
        lines.append("")

    lines.append("# End of WireGuard configuration")
    return "\n".join(lines)


# ============================================================
# PEER ONBOARDING
# ============================================================

def onboard(peer_id):
    """
    Full onboarding workflow:
    - Assign server
    - Generate keys
    - Generate config
    - Generate QR code
    - Send email
    """
    from wireguard.models import WireGuardPeer
    from wireguard.services.email import get_smtp_settings

    logger.info("Starting onboarding for peer %s", peer_id)

    try:
        peer = WireGuardPeer.objects.get(id=peer_id)
    except WireGuardPeer.DoesNotExist:
        logger.error("Peer %s not found", peer_id)
        raise

    if not peer.server:
        peer.server = WireGuardServerService.get_default_server()
        peer.save()

    if not peer.private_key_encrypted:
        private_key, public_key = WireGuardService.generate_keys()
        peer.set_private_key(private_key)
        peer.public_key = public_key
        peer.save()

    conf_content = generate_peer_config(peer)
    conf_filename = f"{peer.name}.conf"

    qr_path = None
    try:
        qr_path = generate_qr(str(peer.id), conf_content)
        peer.qr_path = qr_path
        peer.save()
    except Exception as e:
        logger.warning("QR generation failed: %s", e)

    smtp = get_smtp_settings(force_reload=True)
    if not smtp:
        logger.warning("SMTP not configured — skipping email")
        return

    try:
        server = peer.get_server()
        endpoint = f"{server.endpoint.split(':')[0]}:{server.port}"

        guide = InstallationGuideService.generate(
            GuideContext(
                peer_name=peer.name,
                server_endpoint=endpoint,
                allowed_ips=peer.get_allowed_ips(),
                dns=peer.get_dns(),
                platform=peer.platform,
            )
        )

        html_body = render_to_string(
            "wireguard/emails/onboarding.html",
            {
                "user_name": peer.name,
                "endpoint": endpoint,
                "allowed_ips": peer.get_allowed_ips(),
                "dns": peer.get_dns(),
                "guide": guide,
                "server_name": server.name,
            }
        )

        connection = get_connection(
            backend="django.core.mail.backends.smtp.EmailBackend",
            host=smtp["host"],
            port=smtp["port"],
            username=smtp["username"],
            password=smtp["password"],
            use_tls=True,
            fail_silently=False,
        )

        email = EmailMultiAlternatives(
            subject="Your Secure Network Setup",
            body="Please view this email in HTML format.",
            from_email=smtp["from_email"],
            to=[peer.email],
            connection=connection,
        )

        email.attach_alternative(html_body, "text/html")
        email.attach(conf_filename, conf_content, "text/plain")

        if qr_path and os.path.exists(qr_path):
            with open(qr_path, "rb") as f:
                email.attach(f"qr_{peer.id}.png", f.read(), "image/png")

        sent = email.send()
        logger.info("Email sent to %s (result=%s)", peer.email, sent)

    except Exception:
        logger.exception("Failed to send onboarding email")
        raise