#!/usr/bin/env bash
set -euo pipefail

#====================================================================
# SETUP SUDOERS FOR WIREGUARD AUTO USER
# Maintained by DEVELOPER ANTONY
#====================================================================

SYSTEM_USER="wg-auto"
SUDOERS_FILE="/etc/sudoers.d/${SYSTEM_USER}-wireguard"

# Default WireGuard interface
WG_INTERFACE=${WG_INTERFACE:-wg0}

# Commands to allow without password
WG_COMMANDS=(
  "/usr/bin/wg"
  "/usr/bin/wg-quick"
  "/usr/sbin/iptables-legacy"
)

# Create sudoers file
echo "Updating sudoers for WireGuard commands for user ${SYSTEM_USER}..."

{
  echo "# WireGuard Auto sudoers - DO NOT EDIT MANUALLY"
  echo "# Generated by setup-sudoers.sh"
  echo ""
  for cmd in "${WG_COMMANDS[@]}"; do
    # Allow running the command with any args and no password
    echo "${SYSTEM_USER} ALL=(ALL) NOPASSWD: ${cmd}"
  done
} | sudo tee "$SUDOERS_FILE" >/dev/null

# Set correct permissions
sudo chmod 440 "$SUDOERS_FILE"

echo "✅ Sudoers setup complete for ${SYSTEM_USER}."
echo "Allowed commands:"
printf ' - %s\n' "${WG_COMMANDS[@]}"

#-------------------------------------------------------------------------------------------------------------------------------------
# CREATED AND MAINTAINED BY:      DEVELOPER ANTONY
#                                 developerantony98@gmail.com
#                  GitHub:      ngemuantony
#                  YouTube:     tispadmin
#                  Linkedin:    ngemuantony
#                  TikTok:      tispadmin                   
#-------------------------------------------------------------------------------------------------------------------------------------
