# Generated by Django 6.0.2 on 2026-02-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password_encrypted', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WireGuardPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('public_key', models.CharField(max_length=255)),
                ('private_key_encrypted', models.TextField()),
                ('allowed_ip', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
