# Generated by Django 6.0.2 on 2026-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardpeer',
            name='allowed_ips',
            field=models.CharField(default='0.0.0.0/0', help_text='Comma-separated IPs allowed through tunnel', max_length=255),
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='dns',
            field=models.CharField(default='8.8.8.8,8.8.4.4', help_text='Comma-separated DNS servers', max_length=255),
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS')], default='linux', max_length=20),
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='qr_path',
            field=models.CharField(blank=True, help_text='Path to generated QR code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='server_endpoint',
            field=models.CharField(default='vpn.example.com:51820', help_text='WireGuard server endpoint', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='private_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='public_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
