# Generated by Django 6.0.2 on 2026-02-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0002_wireguardpeer_allowed_ips_wireguardpeer_dns_and_more'),
    ]

    operations = [
    ]
