# Generated by Django 6.0.2 on 2026-02-08 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0003_add_peer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireGuardServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Server name (e.g., "Production VPN")', max_length=100)),
                ('endpoint', models.CharField(help_text='Public endpoint (e.g., vpn.example.com:51820)', max_length=255)),
                ('server_address', models.GenericIPAddressField(help_text='Server VPN IP (e.g., 10.0.0.1/24)')),
                ('private_key_encrypted', models.TextField(help_text='Server private key (encrypted)')),
                ('public_key', models.CharField(help_text='Server public key', max_length=255)),
                ('interface', models.CharField(default='wg0', help_text='Network interface name', max_length=10)),
                ('port', models.IntegerField(default=51820, help_text='UDP port for WireGuard')),
                ('dns', models.CharField(default='8.8.8.8,8.8.4.4', help_text='Comma-separated DNS servers for clients', max_length=255)),
                ('allowed_ips', models.CharField(default='0.0.0.0/0', help_text='Default allowed IPs for new peers', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to disable this server')),
                ('mtu', models.IntegerField(default=1420, help_text='MTU size for WireGuard interface')),
                ('persistent_keepalive', models.IntegerField(default=25, help_text='Persistent keepalive interval (0 to disable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WireGuard Server',
                'verbose_name_plural': 'WireGuard Servers',
            },
        ),
        migrations.AlterModelOptions(
            name='wireguardpeer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server_endpoint',
            field=models.CharField(blank=True, help_text='Override server endpoint (auto-populated from server)', max_length=255),
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='server',
            field=models.ForeignKey(blank=True, help_text='WireGuard server this peer connects to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peers', to='wireguard.wireguardserver'),
        ),
    ]
