# Generated by Django 6.0.2 on 2026-02-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0005_allow_blank_keys_auto_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smtpsettings',
            options={'verbose_name': 'SMTP Setting', 'verbose_name_plural': 'SMTP Settings'},
        ),
        migrations.AlterModelOptions(
            name='wireguardpeer',
            options={'verbose_name': 'WireGuard Peer', 'verbose_name_plural': 'WireGuard Peers'},
        ),
        migrations.AlterModelOptions(
            name='wireguardserver',
            options={'ordering': ['-created_at'], 'verbose_name': 'WireGuard Server', 'verbose_name_plural': 'WireGuard Servers'},
        ),
        migrations.AddIndex(
            model_name='smtpsettings',
            index=models.Index(fields=['host'], name='wireguard_s_host_b1f7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpsettings',
            index=models.Index(fields=['username'], name='wireguard_s_usernam_7315b8_idx'),
        ),
        migrations.AddIndex(
            model_name='wireguardpeer',
            index=models.Index(fields=['email'], name='wireguard_w_email_295caa_idx'),
        ),
        migrations.AddIndex(
            model_name='wireguardpeer',
            index=models.Index(fields=['allowed_ip'], name='wireguard_w_allowed_9743b6_idx'),
        ),
        migrations.AddIndex(
            model_name='wireguardpeer',
            index=models.Index(fields=['is_active'], name='wireguard_w_is_acti_878c96_idx'),
        ),
        migrations.AddIndex(
            model_name='wireguardserver',
            index=models.Index(fields=['endpoint'], name='wireguard_w_endpoin_f21ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='wireguardserver',
            index=models.Index(fields=['is_active'], name='wireguard_w_is_acti_43bea4_idx'),
        ),
    ]
