# Generated by Django 6.0.2 on 2026-02-12 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0006_alter_smtpsettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpsettings',
            name='password_encrypted',
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
