# Generated by Django 6.0.2 on 2026-02-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0007_remove_smtpsettings_password_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wireguardpeer',
            options={'ordering': ['-created_at'], 'verbose_name': 'WireGuard Peer', 'verbose_name_plural': 'WireGuard Peers'},
        ),
        migrations.AlterModelOptions(
            name='wireguardserver',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='allowed_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Peer tunnel IP (no CIDR)', null=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='allowed_ips',
            field=models.CharField(default='0.0.0.0/0', help_text='Client allowed routes', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='dns',
            field=models.CharField(default='8.8.8.8,8.8.4.4', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='qr_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peers', to='wireguard.wireguardserver'),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server_endpoint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='allowed_ips',
            field=models.CharField(default='0.0.0.0/0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='dns',
            field=models.CharField(default='8.8.8.8,8.8.4.4', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='endpoint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='interface',
            field=models.CharField(default='wg0', max_length=10),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='mtu',
            field=models.IntegerField(default=1420),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='persistent_keepalive',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='port',
            field=models.IntegerField(default=51820),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='private_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='server_address',
            field=models.GenericIPAddressField(help_text='e.g. 10.10.10.1/24'),
        ),
    ]
