# Generated by Django 6.0.2 on 2026-02-12 20:35

import django.db.models.deletion
import wireguard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0008_alter_wireguardpeer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wireguardpeer',
            options={'verbose_name': 'WireGuard Peer', 'verbose_name_plural': 'WireGuard Peers'},
        ),
        migrations.AlterModelOptions(
            name='wireguardserver',
            options={'ordering': ['-created_at'], 'verbose_name': 'WireGuard Server', 'verbose_name_plural': 'WireGuard Servers'},
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='allowed_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='allowed_ips',
            field=models.CharField(default='0.0.0.0/0', help_text='Comma-separated IPs allowed through tunnel', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='dns',
            field=models.CharField(default='8.8.8.8,8.8.4.4', help_text='Comma-separated DNS servers', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='qr_path',
            field=models.CharField(blank=True, help_text='Path to generated QR code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server',
            field=models.ForeignKey(blank=True, help_text='WireGuard server this peer connects to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peers', to='wireguard.wireguardserver'),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server_endpoint',
            field=models.CharField(blank=True, help_text='Override server endpoint (auto-populated from server)', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='allowed_ips',
            field=models.CharField(default='0.0.0.0/0', help_text='Default allowed IPs for new peers', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='dns',
            field=models.CharField(default='8.8.8.8,8.8.4.4', help_text='Comma-separated DNS servers for clients', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='endpoint',
            field=models.CharField(help_text='Public endpoint (e.g., vpn.example.com:51820)', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='interface',
            field=models.CharField(default='wg0', help_text='Network interface name', max_length=10),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to disable this server'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='mtu',
            field=models.IntegerField(default=1420, help_text='MTU size for WireGuard interface'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='name',
            field=models.CharField(help_text='Server name (e.g., "Production VPN")', max_length=100),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='persistent_keepalive',
            field=models.IntegerField(default=25, help_text='Persistent keepalive interval (0 to disable)'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='port',
            field=models.IntegerField(default=51820, help_text='UDP port for WireGuard'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='private_key_encrypted',
            field=models.TextField(blank=True, default='', help_text='Server private key (encrypted)'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='public_key',
            field=models.CharField(blank=True, default='', help_text='Server public key', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='server_address',
            field=models.CharField(help_text='Server VPN IP with subnet (e.g., 10.0.0.1/24)', max_length=43, validators=[wireguard.models.validate_cidr]),
        ),
    ]
