# Generated by Django 6.0.2 on 2026-02-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0009_alter_wireguardpeer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardserver',
            name='uplink_interface',
            field=models.CharField(default='eth0', help_text='Interface used for NAT egress', max_length=15),
        ),
    ]
